### ISSUE TITLE
How does this differ from signals?

### ISSUE THREAD

**Issue by MaciekBaron** [DevKnightlie/godot-pub-sub#1]
Just wondering how is this different from using signals

https://docs.godotengine.org/en/3.1/getting_started/step_by_step/signals.html

**Comment by DevKnightlie** [comment]
Functionality is essentially the same as Signals, but with a few differences:

- You don't need to predefine events
- You can use anything for an event key, such as int values
- Publishers and subscribers don't need to know about each other at all

I tried using Signals at scale and found them quite cumbersome to use, so I developed the PubSub class instead.

**Comment by MaciekBaron** [comment]
Ah, that makes sense, thanks for the explanation!
