### ISSUE TITLE
PubSub.publish raises null instances errors

### ISSUE THREAD

**Issue by panmaro** [DevKnightlie/godot-pub-sub#2]
After I switched my project to Godot 3.2, there were an issues with Pub-Sub (_publish_ function and null objects).
The problem was, that the _free_ function isn't called in Godot 3.2 (as I guess).

In my case changing _free_ 
```
func free():
	PubSub.unsubscribe(self)
	.free()
```
to _queue_free_ helped to solve this issue:
```
func queue_free():
	PubSub.unsubscribe(self)
	.queue_free()
```

Regards

**Comment by DevKnightlie** [comment]
Thanks for your message. I've updated the documentation to specify queue_free().
