### ISSUE TITLE
godot's "group" feature did the exactly same thing

### ISSUE THREAD

**Issue by univeous** [DevKnightlie/godot-pub-sub#3]
I think godot already has this function.
for example, the code examples can be rewrite without any addon:
Player class:
```
extends Node
class_name Player

var xp:int = 100

func gain_xp(amount:int)->void:
	xp += amount
	get_tree().call_group("player_xp_gained", "on_player_xp_gained", amount)
```
Monster class:
```
extends Node
class_name Monster

var hit_points:int = 80

func _init():
	add_to_group("player_xp_gained")

func on_player_xp_gained(payload):
	hit_points += payload as int
```

It's obviously more convenient, no addon needed and godot will help node "unsubscribe" automatically.

**Comment by DevKnightlie** [comment]
To an extent, but not all functionality is there or I wouldn't have written the library...
